#%RAML 0.8
title: CosmoHub
version: 0.2.0
baseUri: http://api.cosmohub.pic.es
mediaType: application/json
protocols: [HTTP]

securitySchemes:
  - basic_auth:
      description: >
        HTTP Basic Authentication as described in
        [RFC 1945](http://tools.ietf.org/html/rfc1945#section-11) and
        [RFC 2617](http://tools.ietf.org/html/rfc2617#section-2).
      type: Basic Authentication

securedBy:
  - basic_auth

traits:
  - authenticated:
      usage: >
        Apply to any method that requires an authenticated user.
      
      responses:
        401:
          description: >
            No user is currently authenticated, or the credentials provided are not valid.
  
  - authorized:
      usage: >
        Apply to any method that may restrict access to certain authenticated users.
            
      responses:
        403:
          description: >
            The authenticated user does not have access to this resource.
  
  - parametrized:
      usage: >
        Apply to any method that has to parse data provided by the client.
      
      responses:
        400:
          description: >
            The request is not valid and could not be processed.
        404:
          description: >
            The requested resource does not exist.
  
  - conflictable:
      usage: >
        Apply to any method that may cause some conflict in the database.
      
      responses:
        409:
          description: >
            The request could not be processed due to a conflict in the database.

/user:
  displayName: User profile
  description: >
    Profile information about the authenticated user.
  
  get:
    description: >
      Retrieve profile information about the currently authenticated user.
    
    is: 
      - authenticated
    
    responses:
      200:
        description: >
          Return profile data of the authenticated user.
        
        body:
          application/json:
            example: |
              {
                "id" : 7,
                "email" : "address@example.com",
                "name" :  "John Doe",
                "is_enabled" : true,
                "is_admin" : true,
                "groups" : [
                  "ACME",
                  "Capsule Corp."
                ]
              }
  patch:
    description: >
      Update the details of the currently authenticated user.
    
    is:
      - authenticated
      - parametrized
    
    body:
      application/json:
        example: |
          {
            "password" : "secret",
            "name" : "John Doe"
          }
    
    responses:
      200:
        description: >
          Return updated profile data of the authenticated user.
        
        body:
          application/json:
            example: |
              {
                "id" : 7,
                "email" : "address@example.com",
                "name" :  "John Doe",
                "is_enabled" : true,
                "is_admin" : true,
                "groups" : [
                  "ACME",
                  "Capsule Corp."
                ]
              }
  post:
    description: >
      Register a new user in the service.
    
    securedBy: []
    
    is:
      - parametrized
      - conflictable
    
    body:
      application/json:
        example: |
          {
            "email" : "address@example.com",
            "password" : "secret",
            "name" : "John Doe",
            "groups" : [
              "ACME",
              "Capsule Corp."
            ]
          }
    
    responses:
      201:
        description: >
          The user has been successfully registered.
        
        body:
          application/json:
            example: |
              {
                "id" : 7,
                "email" : "address@example.com",
                "name" :  "John Doe",
                "is_enabled" : true,
                "is_admin" : true,
                "groups" : []
              }

/groups:
  displayName: Groups
  description: >
    Set of all the groups available in the service.
  
  securedBy: []
  
  get:
    description: >
      Retrieve the list of all the groups available in the service.
    
    responses:
      200:
        description: >
          Return a list of group names.
        
        body:
          application/json:
            example: |
              [
                "ACME",
                "Black Mesa",
              ]
    

/catalogs:
  displayName: Catalogs
  description: >
    Set of catalogs available to the authenticated user.
  
  get:
    description: >
      Retrieve the list of catalogs available to the authenticated user.
    
    is: 
      - authenticated
    
    responses:
      200:
        description: >
          Return a list of catalogs
        
        body:
          application/json:
            example: |
              [
                {
                  "id" : 42,
                  "name" : "Galaxy catalog",
                  "version" : "v1.0.5",
                  "description" : "A sample galaxy catalog",
                  "is_public" : true,
                  "is_simulated" : true,
                  "ts_released" : null,
                  "ts_uploaded" : "2015-08-09",
                },
                {
                  "id" : 21,
                  "name" : "Star catalog",
                  "version" : "v2.3.1",
                  "description" : "A sample star catalog",
                  "is_public" : false,
                  "is_simulated" : false,
                  "ts_released" : "2015-10-24",
                  "ts_uploaded" : "2016-05-04",
                }
              ]
  
  /{id}:
    description: >
      Data corresponding to a single catalog, identified by {id}.
    uriParameters:
      id:
        type: integer
        minimum: 1
    
    get:
      description: >
        Retrieve information about the catalog identified by the {id} parameter.
      
      is: 
        - authenticated
        - authorized
        - parametrized
      
      responses:
        200:
          description: >
            Return detailed information about the requested catalog.
          
          body:
            application/json:
              example: |
                {
                  "id" : 42,
                  "name" : "Galaxy catalog",
                  "version" : "v1.0.5",
                  "description" : "A sample galaxy catalog",
                  "summary" : "This galaxy catalog is very interesting. Use it!"
                  "is_public" : true,
                  "is_simulated" : true,
                  "ts_released" : null,
                  "ts_uploaded" : "2015-08-09",
                  "columns" [
                    {
                      "name" : "id",
                      "type" : "integer",
                      "comment" : "Unique identifier of this galaxy",
                      "min" : 1,
                      "max" : 123456
                    },
                    {
                      "name" : "ra",
                      "type" : "double",
                      "comment" : "Right ascension (in degrees)"
                      "min" : 0,
                      "max" : 360
                    },
                    {
                      "name" : "dec",
                      "type" : "double",
                      "comment" : "Declination (in degrees)"
                      "min" : -90,
                      "max" : 90
                    }
                  ],
                  "datasets" : [
                    {
                      "id" : 21,
                      "name" : "Full catalog",
                      "version" : "v1.0",
                      "description" : "The entire catalog with all the columns and objects.",
                      "rows" : 2345678,
                      "ts_defined" : "2016-05-08",
                      "path_readme" : "path/to/some/readme",
                      "recipe" : {
                        "sql" : "SELECT * FROM my_catalog"
                      }
                    },
                    {
                      "id" : 33,
                      "name" : "Brighter galaxies (mag < 20)",
                      "version" : "v1.0",
                      "description" : "A subset of the full catalog, with only the brighter galaxies.",
                      "rows" : 345678,
                      "ts_defined" : "2016-01-18",
                      "path_readme" : "path/to/another/readme",
                      "recipe" : {
                        "sql" : "SELECT * FROM my_catalog WHERE my_mag<20"
                      }
                    }
                  ],
                  "files" : [
                    {
                      "id" : 58,
                      "name" : "Extinction mask",
                      "version" : "v1.0",
                      "description" : "A very interesting extinction mask",
                      "size" : 345678123,
                      "ts_uploaded" : "2016-01-18",
                      "path_readme" : "path/to/its/readme",                      
                      "path_contents" : "path/to/the/actual/mask",
                    }
                  ]
                }

/downloads:
  displayName: Downloads
  description: Download readme files, datasets and query results
  
  /datasets/{id}/readme:
    description: >
      Download the dataset readme identified by the {id} parameter.
    
    get:
      description: >
        Download the requested dataset readme.
      
      is: 
        - authenticated
        - authorized
        - parametrized
      
      responses:
        200:
          description: >
            Entire contents of the requested dataset readme.
          
          body:
            application/octet-stream:
        
        206:
          description: >
            A subset (range) of the requested dataset readme.
          
          body:
            application/octet-stream:
  
  /queries/{id}/results:
    description: >
     Download the results of the query identified by the {id} parameter.
    
    get:
      description: >
        Download the requested query results.
      
      is: 
        - authenticated
        - authorized
        - parametrized
      
      responses:
        200:
          description: >
            Entire contents of the requested query results.
          
          body:
            application/octet-stream:
        
        206:
          description: >
            A subset (range) of the requested query results.
          
          body:
            application/octet-stream:
  
  /files/{id}/readme:
    description: >
      Raw content fo the file readme identified by the {id} parameter.
    
    get:
      description: >
        Download the requested file readme.
      
      is: 
        - authenticated
        - authorized
        - parametrized
      
      responses:
        200:
          description: >
            Entire contents of the requested file readme.
          
          body:
            application/octet-stream:
        
        206:
          description: >
            A subset (range) of the requested file readme.
          
          body:
            application/octet-stream:
    
  /files//{id}/contents:
    description: >
      Raw content fo the file identified by the {id} parameter.
    
    get:
      description: >
        Download the requested file contents.
      
      is: 
        - authenticated
        - authorized
        - parametrized
      
      responses:
        200:
          description: >
            Entire contents of the requested file contents.
          
          body:
            application/octet-stream:
        
        206:
          description: >
            A subset (range) of the requested file contents.
          
          body:
            application/octet-stream:

/queries:
  displayName: Queries
  description: >
    Set of queries performed by the authenticated user.
  
  get:
    description: >
      Retrieve the list of queries performed by the authenticated user.
    
    is: 
      - authenticated
    
    responses:
      200:
        description: >
          Return a list of queries
        
        body:
          application/json:
            example: |
              [
                {
                  "id": 1,
                  "job_id": "application_0001",
                  "rows": 123,
                  "schema": [
                    {
                      "name": "ra",
                      "type": "double"
                    },
                    {
                      "name": "dec",
                      "type": "double"
                    }
                  ],
                  "size": 145236,
                  "path_contents": "/path/to/contents",
                  "sql": "SELECT AVG(ra) AS ra, AVG(dec) AS dec FROM micecat_v2_0_2",
                  "status": "COMPLETED",
                  "ts_created": "2016-06-25",
                  "ts_finished": "2016-06-25",
                  "ts_started": "2016-06-25"
                },
                {
                  "id": 2,
                  "job_id": "application_0002",
                  "rows": 456,
                  "schema": [
                    {
                      "name": "ra",
                      "type": "double"
                    },
                    {
                      "name": "dec",
                      "type": "double"
                    }
                  ],
                  "size": 145236,
                  "path_contents": "/path/to/contents",
                  "sql": "SELECT ra, dec FROM micecat_v2_0_2 LIMIT 456",
                  "status": "PENDING",
                  "ts_created": "2016-06-25",
                  "ts_finished": null,
                  "ts_started": null
                }
              ]
  
  post:
    description: >
      Submit a new query for processing.
    
    is: 
      - authenticated
      - parametrized
    
    body:
      application/json:
        example: |
          {
            "sql" : "SELECT id, ra, dec, FROM acme"
          }
    
    responses:
      201:
        description: >
          The query has been successfully submitted.
        
        body:
          application/json:
            example: |
              {
                "id": 93,
                "job_id": null,
                "path_contents": null,
                "rows": null,
                "schema": null,
                "size": null,
                "sql": "SELECT ra_gal, dec_gal FROM micecat_v2_0_2 LIMIT 20",
                "status": "PENDING",
                "ts_created": "2016-06-25",
                "ts_finished": null,
                "ts_started": null
              }
